# Generated by Django 5.0.4 on 2024-06-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_inquiry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('beds', models.IntegerField(default=1)),
                ('bathtub', models.IntegerField(default=1)),
                ('wifi', models.BooleanField(default=True)),
                ('shuttle', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='offers/')),
            ],
        ),
    ]
