# Generated by Django 5.0.4 on 2024-06-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='features',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_type',
            new_name='destTitle',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='available',
            new_name='wifi',
        ),
        migrations.AddField(
            model_name='room',
            name='bathtub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='bed',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='shuttle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
