# Generated by Django 5.0.4 on 2024-06-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_features_room_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bed',
            new_name='beds',
        ),
    ]
